"""
Hand-curated platform data for each of the 15 LA City Council members,
extracted from campaign websites (primary source) with fallback to official
council bio pages or reputable news outlets (LAist, Wikipedia, Ballotpedia).

Source notes per member indicate the retrieval path used.
"""

PLATFORMS = {
    1: {
        "district": 1,
        "name": "Eunisses Hernandez",
        "party_affiliation": "Democratic",
        "campaign_website_url": "https://www.eunissesforthepeople.com/",
        "source_note": "Campaign site eunissesforthepeople.com",
        "key_issues": [
            "Housing & Tenant Rights",
            "Immigration & Sanctuary",
            "Public Safety & Crisis Response",
            "Budget Equity & Community Investment",
            "Homelessness & Interim Housing",
        ],
        "campaign_promises": [
            "Secure the strongest tenant protections in 40 years and reduce evictions in District 1",
            "Expand unarmed crisis response as an alternative to armed policing (including $4.4M pilot expansion)",
            "Open and operate interim housing models like the Northeast New Beginnings site",
            "Co-author and defend LA's Sanctuary City ordinance to protect immigrants",
            "Shelter and house thousands of homeless Angelenos through permanent housing pipelines",
            "Secure $25+ million for MacArthur Park safety and services improvements",
            "Redirect city budget away from police recruitment toward community care",
            "Block harmful developments like the proposed Lincoln Heights trucking depot",
            "Address environmental justice — brownfields and orphaned oil wells legislation",
            "Operate a Mobile Overdose Response Unit and Peace Ambassador program",
            "Reopen community spaces for small food vendors (e.g., Cypress Park Commissary)",
        ],
        "endorsements": [],
    },
    2: {
        "district": 2,
        "name": "Adrin Nazarian",
        "party_affiliation": "Democratic",
        "campaign_website_url": "https://www.adrinnazarian.com/",
        "source_note": "Campaign site adrinnazarian.com returned timeouts; platform drawn from Wikipedia and LA/search coverage",
        "key_issues": [
            "Housing & Affordability",
            "Public Safety",
            "Transit-Oriented Development",
            "Senior Services",
            "Tenant Protections",
        ],
        "campaign_promises": [
            "Advocate smart, balanced policies to address LA's housing crisis without stifling growth",
            "Champion transit-oriented development that pairs affordable housing with transportation infrastructure",
            "Implement new tenant protections (built on his State Assembly record)",
            "Preserve and expand affordable housing stock in the Valley",
            "Collaborate with law enforcement on comprehensive, community-based public safety strategies",
            "Streamline access to senior services",
            "Expand mass transit access in the San Fernando Valley",
            "Protect immigrants and diverse communities (co-authored protections for Armenians, Assyrians, LGBTQ+ individuals)",
            "Co-introduce motions to protect renters from extreme heat via indoor temperature standards",
        ],
        "endorsements": [
            "Los Angeles League of Conservation Voters",
        ],
    },
    3: {
        "district": 3,
        "name": "Bob Blumenfield",
        "party_affiliation": "Democratic",
        "campaign_website_url": None,
        "source_note": "No active 2024/2026 campaign site; platform drawn from official council bio cd3.lacity.gov (403 direct; content via WebSearch)",
        "key_issues": [
            "Public Safety & Emergency Preparedness",
            "Infrastructure & Beautification",
            "Homelessness",
            "City Budget & Technology Modernization",
            "Parks & Open Space",
        ],
        "campaign_promises": [
            "Craft the City budget to maximize public dollars and transparency",
            "Transform the City's technology infrastructure to more effectively manage resources and services",
            "Lead the Reseda Rising Initiative — public infrastructure investment and public-private partnerships",
            "Deliver the $27 million LA Kings branded public ice rink as an anchor for Reseda",
            "Create the Canoga Park Arts District and expand parks/open space in the Valley",
            "Create more homeless shelter beds in CD3 than the 2020 homeless count population in the district",
            "Ban the sale and manufacture of new fur products in Los Angeles (enacted 2019, effective 2021)",
            "Co-introduce tenant protection from extreme heat via indoor temperature standards",
            "Improve emergency preparedness across the district",
            "Beautification and traffic reduction projects as quality-of-life priorities",
        ],
        "endorsements": [],
    },
    4: {
        "district": 4,
        "name": "Nithya Raman",
        "party_affiliation": "Democratic",
        "campaign_website_url": "https://www.nithyaforthecity.com/",
        "source_note": "Campaign site nithyaforthecity.com (currently a mayoral campaign site; CD4 platform aligned)",
        "key_issues": [
            "Housing Affordability & Production",
            "Renter Protections & Preventing Displacement",
            "Homelessness Response",
            "Government Efficiency & Transparency",
        ],
        "campaign_promises": [
            "Establish a permitting shot clock of 60-120 days for housing approvals",
            "Allow gentle density (duplexes, triplexes, fourplexes) near transit in single-family areas",
            "Convert empty office buildings to residential with reduced fees",
            "Create a unified Super NOFA funding window for affordable housing projects",
            "Legalize factory-built housing and mass timber construction methods",
            "Streamline ADU approvals and permitting",
            "Launch a dedicated Office of Tenant Protections with case management",
            "Partner with LA Superior Court to prevent evictions through mediation and rent relief",
            "Create an Office of Home-Sharing to crack down on illegal short-term rentals in rent-controlled units",
            "Expand Time Limited Subsidies short-term rental vouchers with case management",
            "Deploy street medicine teams citywide for health and mental health care",
            "Establish unarmed crisis response for mental health and substance use calls",
            "Fully resource a Bureau of Homelessness Oversight with dedicated staff",
            "Implement performance-based budgeting and public dashboard tracking homelessness spend",
            "Audit stalled homeless housing projects and push completion",
        ],
        "endorsements": [],
    },
    5: {
        "district": 5,
        "name": "Katy Yaroslavsky",
        "party_affiliation": "Democratic",
        "campaign_website_url": "https://www.katyforla.com/",
        "source_note": "Campaign site katyforla.com",
        "key_issues": [
            "Homelessness & Housing",
            "Public Safety",
            "Climate & Environmental Sustainability",
            "Transit & Infrastructure",
        ],
        "campaign_promises": [
            "Reduce street homelessness in CD5 (27% reduction achieved in first two years)",
            "Triple interim housing beds in CD5",
            "Expand tenant protections for renters",
            "Secure funding for domestic violence survivors",
            "Increase police presence on patrol while investing in smarter public safety",
            "Phase out oil drilling in residential zones",
            "Plant hundreds of trees across the district",
            "Connect and expand bicycle infrastructure",
            "Enhance neighborhood cleanliness and city services",
            "Leverage the Metro D (Purple) Line extension for transit-oriented investment",
            "Prepare the district for the 2028 Olympics",
        ],
        "endorsements": [],
    },
    6: {
        "district": 6,
        "name": "Imelda Padilla",
        "party_affiliation": "Democratic",
        "campaign_website_url": "https://imeldapadilla.com/",
        "source_note": "Campaign site imeldapadilla.com",
        "key_issues": [
            "Unsheltered Population & Housing",
            "Public Safety",
            "Economic Development",
            "Built Environment & Transportation",
            "Parks, Libraries & Youth Programs",
        ],
        "campaign_promises": [
            "Implement an immediate solution to the unhoused crisis through encampment remediation",
            "Connect unhoused individuals to housing, employment, and health services",
            "Increase affordable housing options that keep homeless residents connected to family support",
            "Address unintended consequences of municipal code 85.02 regarding RV parking in industrial areas",
            "Shift from reactive to preventative policing models that reduce incarceration",
            "Expand community-based 911 response pairing social workers with mental health calls",
            "Streamline business licensing and startup processes to reduce barriers",
            "Promote green jobs in vacant industrial buildings",
            "Ensure Van Nuys Corridor Light-Rail and California High Speed Rail do not displace residents",
            "Continue sidewalk repairs and ADA ramp installations",
            "Invest in water-saving infrastructure",
            "Increase library operating hours and digital access",
            "Restore youth programs modeled on the former LA City Youth Commission",
            "Fund recreational programming and seasonal youth employment",
        ],
        "endorsements": [
            "Los Angeles League of Conservation Voters",
        ],
    },
    7: {
        "district": 7,
        "name": "Monica Rodriguez",
        "party_affiliation": "Democratic",
        "campaign_website_url": None,
        "source_note": "monicaforcitycouncil.com redirects to an unrelated domain; platform drawn from cd7.lacity.gov coverage",
        "key_issues": [
            "Homelessness & RV-to-Home",
            "Public Safety",
            "Wildfire Response & Fire Department",
            "Neighborhood Infrastructure",
            "Economic Resiliency",
        ],
        "campaign_promises": [
            "Expand the RV to Home pilot program citywide (permanently removed 100+ RVs; housed 146 individuals)",
            "Establish a dedicated Department of Homelessness to break organizational silos",
            "Improve transparency and coordination across homelessness service agencies",
            "Chair the Public Safety Committee with focus on response-time and resource allocation",
            "Fund and hire LAFD Wildland Hands Crews to respond to wildfires",
            "Invest in equestrian communities and keep equestrian zoning intact",
            "Advance neighborhood infrastructure and services (sidewalks, streetlights, tree canopy)",
            "Support economic resiliency for small businesses in the Northeast Valley",
            "Push innovation and effectiveness in city government operations",
            "Invest in at-risk youth intervention programs and family support",
        ],
        "endorsements": [],
    },
    8: {
        "district": 8,
        "name": "Marqueece Harris-Dawson",
        "party_affiliation": "Democratic",
        "campaign_website_url": "https://www.marqueeceharris-dawson.com/",
        "source_note": "Campaign site marqueeceharris-dawson.com",
        "key_issues": [
            "Economic Development in South LA",
            "Housing & Homelessness",
            "Violence Prevention & Community Policing",
            "Arts & Cultural Preservation",
            "Quality Public Jobs",
        ],
        "campaign_promises": [
            "Chair the Planning, Land Use and Management (PLUM) Committee",
            "Introduce policies combating homelessness rooted in community-based services",
            "Promote creation of quality public-sector jobs",
            "Support clean streets initiatives across South LA",
            "Advance community policing strategies and violence interruption",
            "Complete the Destination Crenshaw 1.3-mile public art / cultural corridor",
            "Preserve legacy businesses along the Crenshaw corridor",
            "Invest in South LA economic development and small business support",
            "Lead as Council President to drive citywide priorities",
        ],
        "endorsements": [
            "Los Angeles County Democratic Party",
            "Mayor Eric Garcetti (prior)",
            "Congressmember Karen Bass (prior)",
            "State Senator Holly Mitchell",
            "Teamsters Local 396",
            "SEIU",
            "UFCW Local 770",
            "Planned Parenthood Advocacy Project LA",
        ],
    },
    9: {
        "district": 9,
        "name": "Curren D. Price Jr.",
        "party_affiliation": "Democratic",
        "campaign_website_url": None,
        "source_note": "No active campaign site located; platform drawn from cd9.lacity.gov and Wikipedia. Note: Price faces criminal corruption charges (2023, 2025).",
        "key_issues": [
            "Housing Affordability & Supply",
            "Economic Development",
            "Immigrant Families",
            "Parks & Recreation",
            "Workers' Rights",
        ],
        "campaign_promises": [
            "Expand Permanent Supportive Housing (PSH), Affordable Housing, and Market Rate Housing",
            "Deliver 700+ affordable units and 800+ PSH units in the CD9 construction pipeline",
            "Attract billions in private investment to District 9 projects",
            "Chair the Economic, Community Development and Jobs Committee",
            "Secure $60M+ for parks and recreation improvements across District 9",
            "Open a CD9 Neighborhood Resource Center with CRCD and CHIRLA",
            "Protect immigrant communities through city-level advocacy and funding",
            "Support taxpayer-subsidy oversight for hotel developments downtown",
            "Advance workers' rights legislation (hotel/hospitality, wage theft)",
        ],
        "endorsements": [],
    },
    10: {
        "district": 10,
        "name": "Heather Hutt",
        "party_affiliation": "Democratic",
        "campaign_website_url": "https://www.heatherhutt.com/",
        "source_note": "Campaign site heatherhutt.com (tagline: 'Potholes. Not Politics.')",
        "key_issues": [
            "Addressing Homelessness",
            "Creating Jobs",
            "Improving Public Services",
        ],
        "campaign_promises": [
            "Address homelessness through interim and permanent housing programs",
            "Create jobs and workforce opportunities in the community",
            "Improve quality of public services (street conditions, sanitation, lighting)",
            "Emphasize public service over partisan politics ('Potholes. Not Politics.')",
            "Healthcare advocacy and support for immigrants and DACA recipients",
            "Leverage experience as California's first Black U.S. Senate State Director for federal partnerships",
            "Advocate for women and people of color in healthcare access",
        ],
        "endorsements": [],
    },
    11: {
        "district": 11,
        "name": "Traci Park",
        "party_affiliation": "Democratic",
        "campaign_website_url": "https://tracipark.com/",
        "source_note": "Campaign site tracipark.com (timed out on direct fetch; content drawn from WebSearch summary and official CD11 press)",
        "key_issues": [
            "Public Safety",
            "Homelessness",
            "Housing (balanced development)",
            "Quality of Life & Clean Streets",
        ],
        "campaign_promises": [
            "Launch the 'A Safer 11 for a Better 11' comprehensive public safety package",
            "Deploy Automated License Plate Reader (ALPR) cameras across CD11",
            "House the CIRCLE Team for unarmed rapid response to non-violent emergencies",
            "Expand mental health and addiction services and LAPD Mental Evaluation Unit",
            "Support gang- and at-risk-youth intervention programs (Helper Foundation)",
            "Supplement LAPD with unarmed response models where appropriate",
            "Clear homeless encampments and move hundreds indoors with services",
            "Introduce motions supporting Governor Newsom's model ordinance on encampments",
            "Support community-informed housing development reflecting Westside character",
            "Prevent homelessness through upstream tenant-assistance programs",
        ],
        "endorsements": [],
    },
    12: {
        "district": 12,
        "name": "John Lee",
        "party_affiliation": "Independent (former Republican; only non-Democrat on LA City Council)",
        "campaign_website_url": None,
        "source_note": "No active campaign site located; platform drawn from cd12.lacity.gov and Wikipedia. Party affiliation corrected: John Lee is registered independent, not Democratic.",
        "key_issues": [
            "Public Safety & LAPD Support",
            "Core City Services",
            "Homelessness (job training model)",
            "Clean Streets & Illegal Dumping",
            "Local Business Support",
        ],
        "campaign_promises": [
            "Chair the Public Safety Committee and oppose defunding the LAPD",
            "Deploy Neighborhood Safety Teams — police patrols focused on business corridors",
            "Expand the Devonshire PALS Youth Center (police + at-risk youth programming)",
            "Run the CD12 Rapid Response program combating illegal dumping",
            "Scale the Clean Streets, Clean Starts program citywide (began in CD12)",
            "Support closure of the Aliso Canyon natural gas facility",
            "Back urban farming pilot programs using shipping containers",
            "Support limited e-scooter availability in appropriate locations",
            "Keep CD12 the lowest-crime district in the City",
            "Deliver core city services (paving, trash, parks) as a primary focus",
        ],
        "endorsements": [],
    },
    13: {
        "district": 13,
        "name": "Hugo Soto-Martinez",
        "party_affiliation": "Democratic",
        "campaign_website_url": "https://hugo2026.com/",
        "source_note": "Campaign site hugo2026.com (2026 re-election site)",
        "key_issues": [
            "Housing & Tenant Protections",
            "Homelessness",
            "Immigration & Sanctuary City",
            "Public Safety (unarmed crisis response)",
            "Community Infrastructure",
        ],
        "campaign_promises": [
            "Make Los Angeles a Sanctuary City against ICE deportations",
            "Lower rent-hike caps and strengthen anti-harassment protections",
            "Reduce homelessness in CD13 25% through a dedicated prevention team",
            "Expand unarmed crisis response and divert 911 calls from police where appropriate",
            "Remove the Echo Park Lake fence and improve park accessibility",
            "Support entertainment workers' labor strikes (hotel, WGA, SAG-AFTRA)",
            "Install 2.1+ miles of protected bike lanes on Hollywood Boulevard",
            "Build five new playgrounds across the district",
            "Prevent hundreds of families from falling into homelessness via rental assistance",
            "Pass the biggest package of renter protections in a generation",
        ],
        "endorsements": [],
    },
    14: {
        "district": 14,
        "name": "Ysabel Jurado",
        "party_affiliation": "Democratic (also a member of Democratic Socialists of America)",
        "campaign_website_url": None,
        "source_note": "ysabeljurado.la currently redirects to Instagram (no active campaign site); platform drawn from LAist reporting and Wikipedia.",
        "key_issues": [
            "Housing Rights & Tenant Protections",
            "Reimagining Public Safety",
            "Homelessness",
            "Street Safety & Infrastructure",
            "Immigration",
        ],
        "campaign_promises": [
            "Stop the 'eviction to homelessness pipeline' with stronger renter protections",
            "Pass rent control measures and establish a right to counsel in evictions",
            "Implement stricter regulations on eviction practices",
            "Invest in financial and relocation assistance programs for vulnerable tenants",
            "Institute a vacancy tax on unrented/unused properties",
            "Charge a speculation fee to property flippers",
            "Deploy ULA (Universal Rent Assistance / Measure ULA) funds to keep seniors in affordable housing",
            "Expand community land trusts with permanent affordability covenants",
            "Leverage public lands for interim housing (Care First Village model)",
            "Coordinate with Supervisor Solis on Skid Row homelessness solutions",
            "Restore broken street lighting (roughly 70% of CD14 lights non-functional)",
            "Reimagine public safety — skeptical of LAPD expansion given $300M+ liability claims",
            "Increase multi-modal transportation in downtown and Boyle Heights",
            "Reduce traffic fatalities in areas bordering freeways",
        ],
        "endorsements": [],
    },
    15: {
        "district": 15,
        "name": "Tim McOsker",
        "party_affiliation": "Democratic",
        "campaign_website_url": "https://www.timmcosker.com/",
        "source_note": "Campaign site timmcosker.com (homepage + /getthefacts)",
        "key_issues": [
            "Wages & Working Families",
            "Economic Development & Blue Economy",
            "Affordable Housing",
            "Public Safety",
            "Government Efficiency",
        ],
        "campaign_promises": [
            "Raise wages for working families and strengthen local living-wage laws",
            "Protect workers' rights and target companies engaged in wage theft",
            "Build more affordable housing in the Harbor Area and citywide",
            "Eliminate bureaucracy and bring commonsense solutions to homelessness",
            "Coordinate mental health and addiction services with housing",
            "Invest in emergency shelters, transitional housing, and permanent housing",
            "Improve neighborhood safety through community partnerships",
            "Advance the blue economy through AltaSea and related initiatives in San Pedro",
            "Expand outdoor dining platforms and small-business support",
            "Convert county buildings into shelters — e.g., 40-bed shelter project",
            "Build responsive, efficient, and effective city government",
        ],
        "endorsements": [
            "Planned Parenthood",
            "Nurses (unnamed nursing union(s))",
            "Teachers (UTLA per context)",
            "Firefighters (UFLAC per context)",
        ],
    },
}
